### ISSUE TITLE
Autoload files are not generating

### ISSUE THREAD

**Issue by casper123** [dmitrovskiy/ionic-push-php#4]
Hi,
I've been trying to send push via your ionic-push-php lib and i installed it using composer. but for some reason; the composer did not generated autoloader files. 

It generates autolad.php in vendor but actual autolaoder files in composer/ dir aren't there.

**Comment by dmitrovskiy** [comment]
Hello, @casper123 
Do you have the last version of composer?
Have you tried to run composer install without this package in dependencies? Maybe issue not in the package?
Also can you send your composer content to confirm the issue?

**Comment by dmitrovskiy** [comment]
Since this issue seems not to be alive I close it.
