### ISSUE TITLE
Please review ReadMe

### ISSUE THREAD

**Issue by darmie** [dmitrovskiy/ionic-push-php#5]
Readme says `$pusher.notify($notification);` , but in PushProcessor class, `notify` holds two parameters  `$pusher.notify($devices, $notification);` 

Which one of them is appropriate?

**Comment by dmitrovskiy** [comment]
@darmie sorry for delay and thanks for issue. I've fixed README file. So to use pusher you need two params. The first is needed for saying to ionic on which devices it should send notification. And the second is notification which will be sent.
