### ISSUE TITLE
How to send notification in hindi?

### ISSUE THREAD

**Issue by krishna711** [dmitrovskiy/ionic-push-php#7]
It is sending hindi language message as it is. Following hindi text (\u0907\u091a\u094d\u091b\u093e-\u0936\u0915\u094d\u0924\u093f)=>"इच्छा-शक्ति" is coming as \u0907\u091a\u094d\u091b\u093e-\u0936\u0915\u094d\u0924\u093f

Do you know why? i believe this will be quick and easy fix. I am sending via ionic-push-server without any issue in hindi.. waiting for a resolution. thanks in advance..

**Comment by jackvial** [comment]
The results you are seeing are correct. If you log out the encoded text it it will be converted to Hindi. 

Here's an example: https://jsfiddle.net/jackvial/fgrwncb0/

**Comment by dmitrovskiy** [comment]
Thanks @jackvial !
