### ISSUE TITLE
Ionic Beta Push support

### ISSUE THREAD

**Issue by eweap** [dmitrovskiy/ionic-push-php#9]
Hi,

Do you plan to support the Ionic Push Beta (the new version of the platform Ionic push http://docs.ionic.io/v2.0.0-beta/docs/push-sending-push ) now that the alpha is closed (and the alpha ionic endpoint is closed too).

Thank you in advance !

**Comment by dmitrovskiy** [comment]
Hi @eweap unfortunately the main project doesn't use this package. (We've migrated to SNS)
Please feel free to improve the package if you wish.

**Comment by argentinaluiz** [comment]
Hi @dmitrovskiy and @eweap,
I send the pull request with new integration. It tested.

**Comment by eweap** [comment]
Thanks a lot @argentinaluiz , I will give it a try soon !

**Comment by dmitrovskiy** [comment]
Merged. Thanks @argentinaluiz !
